"""phase_02_doctor_and_verification_pipeline

Revision ID: 483329b6e015
Revises: f5f4582cd73c
Create Date: 2026-09-11 16:43:24.035490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483329b6e015'
down_revision: Union[str, Sequence[str], None] = 'f5f4582cd73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('medical_reg_number', sa.String(length=100), nullable=False),
    sa.Column('council_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'INFO_REQUESTED', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status'), nullable=False),
    sa.Column('listing_online', sa.Boolean(), nullable=False),
    sa.Column('video_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_doctors_medical_reg_number'), 'doctors', ['medical_reg_number'], unique=True)
    op.create_index(op.f('ix_doctors_specialty'), 'doctors', ['specialty'], unique=False)
    op.create_index(op.f('ix_doctors_verification_status'), 'doctors', ['verification_status'], unique=False)
    op.create_table('doctor_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('MEDICAL_REG_CERT', 'DEGREE_CERT', 'CLINIC_REG', 'IDENTITY_PROOF', name='document_type'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_documents_doctor_id'), 'doctor_documents', ['doctor_id'], unique=False)
    op.create_table('verification_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_admin_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'INFO_REQUESTED', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status'), nullable=False),
    sa.Column('new_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'INFO_REQUESTED', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status'), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reviews_doctor_id'), 'verification_reviews', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_verification_reviews_reviewer_admin_id'), 'verification_reviews', ['reviewer_admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_reviews_reviewer_admin_id'), table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_doctor_id'), table_name='verification_reviews')
    op.drop_table('verification_reviews')
    op.drop_index(op.f('ix_doctor_documents_doctor_id'), table_name='doctor_documents')
    op.drop_table('doctor_documents')
    op.drop_index(op.f('ix_doctors_verification_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_specialty'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_medical_reg_number'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
