"""clinic_pivot_chemist_and_patient_vault

Revision ID: 8ffcaf8ae60b
Revises: e0b538fa2c65
Create Date: 2026-09-11 18:55:59.184258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffcaf8ae60b'
down_revision: Union[str, Sequence[str], None] = 'e0b538fa2c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_documents_doc_type'), 'patient_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_patient_documents_patient_id'), 'patient_documents', ['patient_id'], unique=False)
    op.drop_constraint(op.f('chemists_user_id_key'), 'chemists', type_='unique')
    op.alter_column('doctors', 'video_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('400.00'))
    op.drop_constraint(op.f('reviews_appointment_id_key'), 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('reviews_appointment_id_key'), 'reviews', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('doctors', 'video_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('400.00'))
    op.create_unique_constraint(op.f('chemists_user_id_key'), 'chemists', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_patient_documents_patient_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_doc_type'), table_name='patient_documents')
    op.drop_table('patient_documents')
    # ### end Alembic commands ###
